%%  Comprehensive test for all ScryNeuro FFI functions
:- use_module(library(ffi)).

lib_path(Path) :-
    ( catch((open('./libscryneuro.dylib', read, S), close(S)), _, fail) ->
        Path = "./libscryneuro.dylib"
    ; catch((open('./libscryneuro.so', read, S), close(S)), _, fail) ->
        Path = "./libscryneuro.so"
    ; throw(error("Could not find libscryneuro.dylib or libscryneuro.so", lib_path/1))
    ).


 init :-
    lib_path(LibPath),
    ( use_foreign_module(LibPath, [
        'spy_init'([], sint32),
        'spy_finalize'([], void),
        'spy_last_error'([], cstr),
        'spy_last_error_clear'([], void),
        'spy_handle_count'([], sint64),
        'spy_drop'([ptr], void),
        'spy_eval'([cstr], ptr),
        'spy_exec'([cstr], sint32),
        'spy_import'([cstr], ptr),
        'spy_getattr'([ptr, cstr], ptr),
        'spy_setattr'([ptr, cstr, ptr], sint32),
        'spy_call0'([ptr], ptr),
        'spy_call1'([ptr, ptr], ptr),
        'spy_call2'([ptr, ptr, ptr], ptr),
        'spy_call3'([ptr, ptr, ptr, ptr], ptr),
        'spy_calln'([ptr, ptr], ptr),
        'spy_invoke0'([ptr, cstr], ptr),
        'spy_invoke1'([ptr, cstr, ptr], ptr),
        'spy_invoke2'([ptr, cstr, ptr, ptr], ptr),
        'spy_invoken'([ptr, cstr, ptr], ptr),
        'spy_to_str'([ptr], cstr),
        'spy_to_repr'([ptr], cstr),
        'spy_to_int'([ptr], sint64),
        'spy_to_float'([ptr], f64),
        'spy_to_bool'([ptr], sint32),
        'spy_from_int'([sint64], ptr),
        'spy_from_float'([f64], ptr),
        'spy_from_bool'([sint32], ptr),
        'spy_from_str'([cstr], ptr),
        'spy_none'([], ptr),
        'spy_is_none'([ptr], sint32),
        'spy_to_json'([ptr], cstr),
        'spy_from_json'([cstr], ptr),
        'spy_list_new'([], ptr),
        'spy_list_append'([ptr, ptr], sint32),
        'spy_list_get'([ptr, sint64], ptr),
        'spy_list_len'([ptr], sint64),
        'spy_dict_new'([], ptr),
        'spy_dict_set'([ptr, cstr, ptr], sint32),
        'spy_dict_get'([ptr, cstr], ptr)
    ]) -> true ; throw(error("Failed to load foreign module (check DYLD_LIBRARY_PATH on macOS or LD_LIBRARY_PATH on Linux)", init/0))).

test :-
    write('1. spy_init: '),
    ffi:'spy_init'(S), write(S), nl,

    write('2. from_int(42)->to_int: '),
    ffi:'spy_from_int'(42, HI),
    ffi:'spy_to_int'(HI, VI),
    write(VI), nl,
    ffi:'spy_drop'(HI),

    write('3. from_float(3.14)->to_float: '),
    ffi:'spy_from_float'(3.14, HF),
    ffi:'spy_to_float'(HF, VF),
    write(VF), nl,
    ffi:'spy_drop'(HF),

    write('4. from_bool(1)->to_bool: '),
    ffi:'spy_from_bool'(1, HB),
    ffi:'spy_to_bool'(HB, VB),
    write(VB), nl,
    ffi:'spy_drop'(HB),

    write('5. from_str(test)->to_str: '),
    ffi:'spy_from_str'("test", HS),
    ffi:'spy_to_str'(HS, VS),
    write(VS), nl,
    ffi:'spy_drop'(HS),

    write('6. eval(2**10): '),
    ffi:'spy_eval'("2**10", HE),
    ffi:'spy_to_int'(HE, VE),
    write(VE), nl,
    ffi:'spy_drop'(HE),

    write('7. exec/eval readback: '),
    ffi:'spy_exec'("_tv = 99", SE),
    write('exec='), write(SE), write(' '),
    ffi:'spy_eval'("_tv", HEV),
    ffi:'spy_to_int'(HEV, VEV),
    write('val='), write(VEV), nl,
    ffi:'spy_drop'(HEV),

    write('8. import math: '),
    ffi:'spy_import'("math", HM),
    write(HM), nl,

    write('9. math.pi: '),
    ffi:'spy_getattr'(HM, "pi", HPI),
    ffi:'spy_to_float'(HPI, VPI),
    write(VPI), nl,
    ffi:'spy_drop'(HPI),

    write('10. math.sqrt(16): '),
    ffi:'spy_getattr'(HM, "sqrt", HSqrt),
    ffi:'spy_from_float'(16.0, H16),
    ffi:'spy_call1'(HSqrt, H16, HRes10),
    ffi:'spy_to_float'(HRes10, VR10),
    write(VR10), nl,
    ffi:'spy_drop'(HSqrt), ffi:'spy_drop'(H16), ffi:'spy_drop'(HRes10),

    write('11. math.factorial(5): '),
    ffi:'spy_from_int'(5, H5),
    ffi:'spy_invoke1'(HM, "factorial", H5, HFact),
    ffi:'spy_to_int'(HFact, VFact),
    write(VFact), nl,
    ffi:'spy_drop'(H5), ffi:'spy_drop'(HFact), ffi:'spy_drop'(HM),

    write('12. none/is_none: '),
    ffi:'spy_none'(HN),
    ffi:'spy_is_none'(HN, IN),
    write(IN), nl,
    ffi:'spy_drop'(HN),

    write('13. repr(42): '),
    ffi:'spy_from_int'(42, HR13),
    ffi:'spy_to_repr'(HR13, VR13),
    write(VR13), nl,
    ffi:'spy_drop'(HR13),

    write('14. list: '),
    ffi:'spy_list_new'(HL),
    ffi:'spy_from_int'(10, H10L),
    ffi:'spy_from_int'(20, H20L),
    ffi:'spy_list_append'(HL, H10L, _),
    ffi:'spy_list_append'(HL, H20L, _),
    ffi:'spy_list_len'(HL, LLen),
    write('len='), write(LLen), write(' '),
    ffi:'spy_list_get'(HL, 0, HLG),
    ffi:'spy_to_int'(HLG, VLG),
    write('get(0)='), write(VLG), nl,
    ffi:'spy_drop'(HLG), ffi:'spy_drop'(H10L), ffi:'spy_drop'(H20L), ffi:'spy_drop'(HL),

    write('15. dict: '),
    ffi:'spy_dict_new'(HD),
    ffi:'spy_from_str'("world", HDV),
    ffi:'spy_dict_set'(HD, "hello", HDV, _),
    ffi:'spy_dict_get'(HD, "hello", HDG),
    ffi:'spy_to_str'(HDG, VDG),
    write(VDG), nl,
    ffi:'spy_drop'(HDG), ffi:'spy_drop'(HDV), ffi:'spy_drop'(HD),

    write('16. JSON: '),
    ffi:'spy_from_json'("[1,2,3]", HJ),
    ffi:'spy_to_json'(HJ, VJ),
    write(VJ), nl,
    ffi:'spy_drop'(HJ),

    write('17. call0 list(): '),
    ffi:'spy_eval'("list", HListCls),
    ffi:'spy_call0'(HListCls, HEmpty),
    ffi:'spy_list_len'(HEmpty, ELen),
    write('len='), write(ELen), nl,
    ffi:'spy_drop'(HEmpty), ffi:'spy_drop'(HListCls),

    write('18. pow(2,10): '),
    ffi:'spy_eval'("pow", HPow),
    ffi:'spy_from_int'(2, HC2),
    ffi:'spy_from_int'(10, HC10),
    ffi:'spy_call2'(HPow, HC2, HC10, HCR),
    ffi:'spy_to_int'(HCR, VCR),
    write(VCR), nl,
    ffi:'spy_drop'(HPow), ffi:'spy_drop'(HC2), ffi:'spy_drop'(HC10), ffi:'spy_drop'(HCR),

    write('19. lambda(1,2,3): '),
    ffi:'spy_eval'("lambda a,b,c: a+b+c", HLam),
    ffi:'spy_from_int'(1, HCA),
    ffi:'spy_from_int'(2, HCB),
    ffi:'spy_from_int'(3, HCC),
    ffi:'spy_call3'(HLam, HCA, HCB, HCC, HCR3),
    ffi:'spy_to_int'(HCR3, VCR3),
    write(VCR3), nl,
    ffi:'spy_drop'(HLam), ffi:'spy_drop'(HCA), ffi:'spy_drop'(HCB), ffi:'spy_drop'(HCC), ffi:'spy_drop'(HCR3),

    write('20. invoke0 upper: '),
    ffi:'spy_from_str'("hello", HSI0),
    ffi:'spy_invoke0'(HSI0, "upper", HU0),
    ffi:'spy_to_str'(HU0, VU0),
    write(VU0), nl,
    ffi:'spy_drop'(HSI0), ffi:'spy_drop'(HU0),

    write('21. invoke2 replace: '),
    ffi:'spy_from_str'("hello world", HSI2),
    ffi:'spy_from_str'("world", HSA1),
    ffi:'spy_from_str'("prolog", HSA2),
    ffi:'spy_invoke2'(HSI2, "replace", HSA1, HSA2, HRI2),
    ffi:'spy_to_str'(HRI2, VRI2),
    write(VRI2), nl,
    ffi:'spy_drop'(HSI2), ffi:'spy_drop'(HSA1), ffi:'spy_drop'(HSA2), ffi:'spy_drop'(HRI2),

    write('22. setattr/getattr: '),
    ffi:'spy_exec'("class _O: pass", _),
    ffi:'spy_eval'("_O()", HOb),
    ffi:'spy_from_int'(99, HOV),
    ffi:'spy_setattr'(HOb, "x", HOV, SAR),
    write('set='), write(SAR), write(' '),
    ffi:'spy_getattr'(HOb, "x", HOX),
    ffi:'spy_to_int'(HOX, VOX),
    write('get='), write(VOX), nl,
    ffi:'spy_drop'(HOV), ffi:'spy_drop'(HOX), ffi:'spy_drop'(HOb),

    write('23. calln sum4: '),
    ffi:'spy_eval'("lambda a,b,c,d: a+b+c+d", HSum4),
    ffi:'spy_list_new'(HArgs),
    ffi:'spy_from_int'(1, HA1),
    ffi:'spy_from_int'(2, HA2),
    ffi:'spy_from_int'(3, HA3),
    ffi:'spy_from_int'(4, HA4),
    ffi:'spy_list_append'(HArgs, HA1, _),
    ffi:'spy_list_append'(HArgs, HA2, _),
    ffi:'spy_list_append'(HArgs, HA3, _),
    ffi:'spy_list_append'(HArgs, HA4, _),
    ffi:'spy_calln'(HSum4, HArgs, HSumRes),
    ffi:'spy_to_int'(HSumRes, VSumRes),
    write(VSumRes), nl,
    ffi:'spy_drop'(HSumRes), ffi:'spy_drop'(HA4), ffi:'spy_drop'(HA3), ffi:'spy_drop'(HA2), ffi:'spy_drop'(HA1),
    ffi:'spy_drop'(HArgs), ffi:'spy_drop'(HSum4),

    write('24. invoken replace: '),
    ffi:'spy_from_str'("hello world", HInvStr),
    ffi:'spy_list_new'(HInvArgs),
    ffi:'spy_from_str'("world", HInvA1),
    ffi:'spy_from_str'("prolog", HInvA2),
    ffi:'spy_list_append'(HInvArgs, HInvA1, _),
    ffi:'spy_list_append'(HInvArgs, HInvA2, _),
    ffi:'spy_invoken'(HInvStr, "replace", HInvArgs, HInvRes),
    ffi:'spy_to_str'(HInvRes, VInvRes),
    write(VInvRes), nl,
    ffi:'spy_drop'(HInvRes), ffi:'spy_drop'(HInvA2), ffi:'spy_drop'(HInvA1), ffi:'spy_drop'(HInvArgs),
    ffi:'spy_drop'(HInvStr),

    write('25. error(1/0): '),
    ffi:'spy_eval'("1/0", HErr),
    write('h='), write(HErr), write(' '),
    ffi:'spy_last_error'(EMsg),
    write(EMsg), nl,
    ffi:'spy_last_error_clear',

    write('26. handle_count: '),
    ffi:'spy_handle_count'(FC),
    write(FC), nl,

    ffi:'spy_finalize',
    write('=== ALL 26 TESTS PASSED ==='), nl.

 :- initialization((init, test)).
