%% ===========================================================================
%% ScryNeuro Real LLM Agent Example (OpenAI-compatible)
%% ===========================================================================
%%
%% Runs against OpenAI-compatible APIs (OpenAI / compatible proxies / local servers).
%% Demonstrates real tools + skills + markdown artifact output.
%% Required configuration:
%%   - OPENAI_API_KEY provided either by shell env OR project .env
%% Optional:
%%   - OPENAI_MODEL      (default: from .env/env if model arg is auto)
%%   - OPENAI_BASE_URL   (default: provider default; can come from env or .env)
%%
%% Run:
%%   LD_LIBRARY_PATH=. scryer-prolog examples/real_llm_agent.pl

:- op(700, xfx, :=).
:- use_module('../prolog/scryer_py').
:- use_module('../prolog/scryer_agent').
:- use_module(library(os)).

run_example(Name, Goal) :-
    catch(Goal, E, (format("[ERROR] ~s failed:~n", [Name]), print_py_error(E), fail)),
    format("[OK] ~s~n", [Name]).

optional_getenv(Key, Default, Value) :-
    ( catch(getenv(Key, V), _, fail) -> Value = V
    ; Value = Default
    ).

test_real_llm_agent :-
    optional_getenv("OPENAI_MODEL", "auto", Model),
    optional_getenv("OPENAI_BASE_URL", "", BaseUrl),

    ( BaseUrl = [] ->
        agent_create(openai_agent, Model, [provider=openai])
    ; agent_create(openai_agent, Model, [provider=openai, base_url=BaseUrl])
    ),

    agent_register_builtin_tools(openai_agent, [web_fetch, shell_exec, read_file, write_file, list_dir, grep_text]),
    agent_load_skill(openai_agent, research, [skills_dir="python/skills"]),
    agent_load_skill(openai_agent, shell_safety, [skills_dir="python/skills"]),

    Prompt = "You are a research agent. Use tools to fetch one public web page related to AI/news, then write a concise markdown report to reports/latest_news.md with sections: Title, Sources, Summary, Key Points (3 bullets). Return a brief final message mentioning the file path.",
    agent_run(openai_agent, Prompt, Out, [max_steps=5, max_auto_tools=4, temperature=0.0, max_tokens=800]),
    format("Real LLM run output: ~s~n", [Out]),

    agent_step(openai_agent, "tool:read_file {\"path\": \"reports/latest_news.md\"}", MarkdownOut, [max_auto_tools=3]),
    format("Generated markdown preview: ~s~n", [MarkdownOut]),

    agent_step(openai_agent, "tool:web_fetch {\"url\": \"https://news.ycombinator.com\", \"timeout\": 15}", FetchOut, [max_auto_tools=3]),
    format("Web fetch output: ~s~n", [FetchOut]),

    agent_step(openai_agent, "tool:write_file {\"path\": \"reports/news_snapshot.md\", \"content\": \"# News Snapshot\\n\\nGenerated by agent.\"}", WriteOut, [max_auto_tools=3]),
    format("Write markdown output: ~s~n", [WriteOut]),

    agent_trace(openai_agent, Trace),
    format("OpenAI trace: ~s~n", [Trace]),

    agent_unload(openai_agent).

:- initialization((
    py_init,
    ( catch(run_example("test_real_llm_agent", test_real_llm_agent), Error, (print_py_error(Error), fail)) ->
        format("=== Real LLM agent example passed ===~n", [])
    ; format("=== Real LLM agent example failed ===~n", [])
    ),
    py_finalize
)).
